import React from "react";
import "./Tablets.css";
import TabletCard from "./TabletCard.js";
import Navbar from "../Navbar/Navbar.js";
const Tablets = () => {
  const tablets = [
    {
      id: 1,
      name: "Paracetamol",
      quantity: 100,
      arrival_date: "2024-04-20",
      expiry_date: "2025-04-20",
      rack_number: "A1",
      manufactured_by: "ABC Pharmaceuticals",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Paracetamol",
      price: 5.99,
      dosage: "500 mg",
      composition: "Paracetamol",
      category: "Pain Reliever",
      formulation: "Tablet",
      instructions:
        "Take 1-2 tablets every 4-6 hours as needed for pain relief.",
      prescription_required: false,
      storage_conditions: "Store at room temperature.",
      side_effects: "May cause mild stomach upset.",
      warnings: "Do not exceed recommended dosage.",
      batch_number: "AB12345",
      country_of_origin: "USA",
      barcode: "1234567890123",
      generic_equivalent: true,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 2,
      name: "Ibuprofen",
      quantity: 75,
      arrival_date: "2024-04-18",
      expiry_date: "2025-04-18",
      rack_number: "B2",
      manufactured_by: "XYZ Pharmaceuticals",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Ibuprofen",
      price: 7.99,
      dosage: "200 mg",
      composition: "Ibuprofen",
      category: "Pain Reliever",
      formulation: "Tablet",
      instructions: "Take 1 tablet every 4-6 hours with food.",
      prescription_required: false,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause stomach irritation.",
      warnings: "Do not take on an empty stomach.",
      batch_number: "CD23456",
      country_of_origin: "UK",
      barcode: "2345678901234",
      generic_equivalent: true,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 3,
      name: "Aspirin",
      quantity: 50,
      arrival_date: "2024-04-15",
      expiry_date: "2025-04-15",
      rack_number: "C3",
      manufactured_by: "PharmaCorp",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Aspirin",
      price: 4.49,
      dosage: "81 mg",
      composition: "Aspirin",
      category: "Pain Reliever",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily with a glass of water.",
      prescription_required: false,
      storage_conditions: "Store in a dry place.",
      side_effects: "May cause gastric irritation.",
      warnings: "Not recommended for children under 12.",
      batch_number: "EF34567",
      country_of_origin: "Germany",
      barcode: "3456789012345",
      generic_equivalent: true,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 4,
      name: "Omeprazole",
      quantity: 80,
      arrival_date: "2024-04-12",
      expiry_date: "2025-04-12",
      rack_number: "D4",
      manufactured_by: "MediPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Omeprazole",
      price: 12.99,
      dosage: "20 mg",
      composition: "Omeprazole",
      category: "Antacid",
      formulation: "Capsule",
      instructions: "Take 1 capsule daily before a meal.",
      prescription_required: false,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause headache or nausea.",
      warnings: "Do not crush or chew capsules.",
      batch_number: "GH45678",
      country_of_origin: "India",
      barcode: "4567890123456",
      generic_equivalent: true,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 5,
      name: "Cetirizine",
      quantity: 60,
      arrival_date: "2024-04-10",
      expiry_date: "2025-04-10",
      rack_number: "E5",
      manufactured_by: "HealthPharma",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Cetirizine",
      price: 8.49,
      dosage: "10 mg",
      composition: "Cetirizine",
      category: "Antihistamine",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily with or without food.",
      prescription_required: false,
      storage_conditions: "Store in a dry place.",
      side_effects: "May cause drowsiness.",
      warnings: "Avoid alcohol while taking this medication.",
      batch_number: "IJ56789",
      country_of_origin: "France",
      barcode: "5678901234567",
      generic_equivalent: true,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 6,
      name: "Loratadine",
      quantity: 70,
      arrival_date: "2024-04-08",
      expiry_date: "2025-04-08",
      rack_number: "F6",
      manufactured_by: "GlobalPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Loratadine",
      price: 9.99,
      dosage: "10 mg",
      composition: "Loratadine",
      category: "Antihistamine",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily with water.",
      prescription_required: false,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause dry mouth or headache.",
      warnings: "Consult a doctor if pregnant or breastfeeding.",
      batch_number: "KL67890",
      country_of_origin: "Japan",
      barcode: "6789012345678",
      generic_equivalent: true,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 7,
      name: "Simvastatin",
      quantity: 90,
      arrival_date: "2024-04-06",
      expiry_date: "2025-04-06",
      rack_number: "G7",
      manufactured_by: "PharmaMed",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Simvastatin",
      price: 15.99,
      dosage: "20 mg",
      composition: "Simvastatin",
      category: "Cholesterol Lowering Agent",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the evening.",
      prescription_required: true,
      storage_conditions: "Store at room temperature.",
      side_effects: "May cause muscle pain or weakness.",
      warnings:
        "Avoid grapefruit and grapefruit juice while taking this medication.",
      batch_number: "MN78901",
      country_of_origin: "Switzerland",
      barcode: "7890123456789",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 8,
      name: "Metformin",
      quantity: 110,
      arrival_date: "2024-04-04",
      expiry_date: "2025-04-04",
      rack_number: "H8",
      manufactured_by: "BioPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Metformin",
      price: 12.49,
      dosage: "500 mg",
      composition: "Metformin",
      category: "Antidiabetic",
      formulation: "Tablet",
      instructions: "Take 1 tablet twice daily with meals.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause gastrointestinal upset.",
      warnings: "Monitor blood sugar regularly.",
      batch_number: "OP89012",
      country_of_origin: "Germany",
      barcode: "8901234567890",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 9,
      name: "Amoxicillin",
      quantity: 40,
      arrival_date: "2024-04-02",
      expiry_date: "2025-04-02",
      rack_number: "I9",
      manufactured_by: "MediTech",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Amoxicillin",
      price: 8.99,
      dosage: "500 mg",
      composition: "Amoxicillin",
      category: "Antibiotic",
      formulation: "Capsule",
      instructions: "Take 1 capsule every 8 hours with food.",
      prescription_required: true,
      storage_conditions: "Store in a dry place.",
      side_effects: "May cause diarrhea or rash.",
      warnings: "Complete the full course of medication.",
      batch_number: "QR90123",
      country_of_origin: "USA",
      barcode: "9012345678901",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 10,
      name: "Atorvastatin",
      quantity: 85,
      arrival_date: "2024-03-31",
      expiry_date: "2025-03-31",
      rack_number: "J10",
      manufactured_by: "PharmaTech",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Atorvastatin",
      price: 18.99,
      dosage: "40 mg",
      composition: "Atorvastatin",
      category: "Cholesterol Lowering Agent",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the evening.",
      prescription_required: true,
      storage_conditions: "Store at room temperature.",
      side_effects: "May cause muscle pain or weakness.",
      warnings:
        "Avoid grapefruit and grapefruit juice while taking this medication.",
      batch_number: "ST01234",
      country_of_origin: "Canada",
      barcode: "0123456789012",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 11,
      name: "Diazepam",
      quantity: 65,
      arrival_date: "2024-03-29",
      expiry_date: "2025-03-29",
      rack_number: "K11",
      manufactured_by: "HealthCare",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Diazepam",
      price: 10.99,
      dosage: "5 mg",
      composition: "Diazepam",
      category: "Anxiolytic",
      formulation: "Tablet",
      instructions: "Take 1-2 tablets as needed for anxiety.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause drowsiness or dizziness.",
      warnings: "Avoid alcohol while taking this medication.",
      batch_number: "UV12345",
      country_of_origin: "UK",
      barcode: "1234567890123",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 12,
      name: "Ciprofloxacin",
      quantity: 55,
      arrival_date: "2024-03-27",
      expiry_date: "2025-03-27",
      rack_number: "L12",
      manufactured_by: "MediCare",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Ciprofloxacin",
      price: 9.49,
      dosage: "500 mg",
      composition: "Ciprofloxacin",
      category: "Antibiotic",
      formulation: "Tablet",
      instructions: "Take 1 tablet every 12 hours with a full glass of water.",
      prescription_required: true,
      storage_conditions: "Store in a dry place.",
      side_effects: "May cause nausea or diarrhea.",
      warnings: "Avoid prolonged exposure to sunlight.",
      batch_number: "WX23456",
      country_of_origin: "Germany",
      barcode: "2345678901234",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 13,
      name: "Furosemide",
      quantity: 95,
      arrival_date: "2024-03-25",
      expiry_date: "2025-03-25",
      rack_number: "M13",
      manufactured_by: "PharmaCare",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Furosemide",
      price: 7.99,
      dosage: "40 mg",
      composition: "Furosemide",
      category: "Diuretic",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the morning.",
      prescription_required: true,
      storage_conditions: "Store at room temperature.",
      side_effects: "May cause dehydration or electrolyte imbalance.",
      warnings: "Monitor potassium levels regularly.",
      batch_number: "YZ34567",
      country_of_origin: "USA",
      barcode: "3456789012345",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 14,
      name: "Levothyroxine",
      quantity: 120,
      arrival_date: "2024-03-23",
      expiry_date: "2025-03-23",
      rack_number: "N14",
      manufactured_by: "BioPharma",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Levothyroxine",
      price: 11.99,
      dosage: "100 mcg",
      composition: "Levothyroxine",
      category: "Thyroid Hormone",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily on an empty stomach.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause palpitations or weight loss.",
      warnings:
        "Do not switch between different brands of levothyroxine without consulting a doctor.",
      batch_number: "AB45678",
      country_of_origin: "France",
      barcode: "4567890123456",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 15,
      name: "Metoprolol",
      quantity: 105,
      arrival_date: "2024-03-21",
      expiry_date: "2025-03-21",
      rack_number: "O15",
      manufactured_by: "MediPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Metoprolol",
      price: 14.49,
      dosage: "50 mg",
      composition: "Metoprolol",
      category: "Beta Blocker",
      formulation: "Tablet",
      instructions: "Take 1 tablet twice daily with or without food.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause fatigue or dizziness.",
      warnings: "Do not stop taking suddenly without consulting a doctor.",
      batch_number: "CD56789",
      country_of_origin: "Germany",
      barcode: "5678901234567",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 16,
      name: "Ondansetron",
      quantity: 75,
      arrival_date: "2024-03-19",
      expiry_date: "2025-03-19",
      rack_number: "P16",
      manufactured_by: "GlobalPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Ondansetron",
      price: 13.99,
      dosage: "4 mg",
      composition: "Ondansetron",
      category: "Antiemetic",
      formulation: "Tablet",
      instructions: "Take 1 tablet 30 minutes before chemotherapy or surgery.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause headache or constipation.",
      warnings: "Do not take if allergic to ondansetron.",
      batch_number: "DE67890",
      country_of_origin: "India",
      barcode: "6789012345678",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 17,
      name: "Prednisone",
      quantity: 95,
      arrival_date: "2024-03-17",
      expiry_date: "2025-03-17",
      rack_number: "Q17",
      manufactured_by: "PharmaCorp",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Prednisone",
      price: 8.99,
      dosage: "10 mg",
      composition: "Prednisone",
      category: "Corticosteroid",
      formulation: "Tablet",
      instructions: "Take as directed by your doctor.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause weight gain or mood changes.",
      warnings: "Do not stop taking suddenly without consulting a doctor.",
      batch_number: "EF78901",
      country_of_origin: "USA",
      barcode: "7890123456789",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 18,
      name: "Sertraline",
      quantity: 110,
      arrival_date: "2024-03-15",
      expiry_date: "2025-03-15",
      rack_number: "R18",
      manufactured_by: "XYZ Pharmaceuticals",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Sertraline",
      price: 11.49,
      dosage: "50 mg",
      composition: "Sertraline",
      category: "Antidepressant",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily with or without food.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause nausea or headache.",
      warnings: "Do not take with MAOIs or within 14 days of stopping an MAOI.",
      batch_number: "FG89012",
      country_of_origin: "UK",
      barcode: "8901234567890",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 19,
      name: "Lisinopril",
      quantity: 80,
      arrival_date: "2024-03-13",
      expiry_date: "2025-03-13",
      rack_number: "S19",
      manufactured_by: "HealthPharma",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Lisinopril",
      price: 9.99,
      dosage: "10 mg",
      composition: "Lisinopril",
      category: "Antihypertensive",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily with or without food.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause dizziness or cough.",
      warnings:
        "Avoid potassium supplements or salt substitutes containing potassium while taking this medication.",
      batch_number: "GH01234",
      country_of_origin: "France",
      barcode: "0123456789012",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 20,
      name: "Hydrochlorothiazide",
      quantity: 100,
      arrival_date: "2024-03-11",
      expiry_date: "2025-03-11",
      rack_number: "T20",
      manufactured_by: "GlobalPharm",
      image_url:
        "https://dummyimage.com/200x200/000/fff&text=Hydrochlorothiazide",
      price: 7.49,
      dosage: "25 mg",
      composition: "Hydrochlorothiazide",
      category: "Diuretic",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the morning.",
      prescription_required: true,
      storage_conditions: "Store in a dry place.",
      side_effects: "May cause dizziness or dehydration.",
      warnings: "Monitor electrolyte levels regularly.",
      batch_number: "IJ23456",
      country_of_origin: "India",
      barcode: "2345678901234",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 21,
      name: "Metronidazole",
      quantity: 75,
      arrival_date: "2024-03-09",
      expiry_date: "2025-03-09",
      rack_number: "U21",
      manufactured_by: "MediTech",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Metronidazole",
      price: 8.99,
      dosage: "500 mg",
      composition: "Metronidazole",
      category: "Antibiotic",
      formulation: "Tablet",
      instructions: "Take as directed by your doctor.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause nausea or metallic taste.",
      warnings: "Avoid alcohol while taking this medication.",
      batch_number: "KL34567",
      country_of_origin: "USA",
      barcode: "3456789012345",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 22,
      name: "Warfarin",
      quantity: 90,
      arrival_date: "2024-03-07",
      expiry_date: "2025-03-07",
      rack_number: "V22",
      manufactured_by: "PharmaMed",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Warfarin",
      price: 12.99,
      dosage: "5 mg",
      composition: "Warfarin",
      category: "Anticoagulant",
      formulation: "Tablet",
      instructions: "Take as directed by your doctor.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause bleeding or bruising.",
      warnings: "Regularly monitor INR levels.",
      batch_number: "MN45678",
      country_of_origin: "Switzerland",
      barcode: "4567890123456",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 23,
      name: "Gabapentin",
      quantity: 105,
      arrival_date: "2024-03-05",
      expiry_date: "2025-03-05",
      rack_number: "W23",
      manufactured_by: "BioPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Gabapentin",
      price: 9.49,
      dosage: "300 mg",
      composition: "Gabapentin",
      category: "Anticonvulsant",
      formulation: "Capsule",
      instructions: "Take as directed by your doctor.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause drowsiness or dizziness.",
      warnings:
        "Avoid driving or operating machinery while taking this medication.",
      batch_number: "OP67890",
      country_of_origin: "Germany",
      barcode: "6789012345678",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 24,
      name: "Clarithromycin",
      quantity: 60,
      arrival_date: "2024-03-03",
      expiry_date: "2025-03-03",
      rack_number: "X24",
      manufactured_by: "HealthPharma",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Clarithromycin",
      price: 11.99,
      dosage: "500 mg",
      composition: "Clarithromycin",
      category: "Antibiotic",
      formulation: "Tablet",
      instructions: "Take as directed by your doctor.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause nausea or diarrhea.",
      warnings: "Complete the full course of medication.",
      batch_number: "QR01234",
      country_of_origin: "France",
      barcode: "0123456789012",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 25,
      name: "Atenolol",
      quantity: 110,
      arrival_date: "2024-03-01",
      expiry_date: "2025-03-01",
      rack_number: "Y25",
      manufactured_by: "PharmaTech",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Atenolol",
      price: 8.49,
      dosage: "50 mg",
      composition: "Atenolol",
      category: "Beta Blocker",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the morning.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause fatigue or dizziness.",
      warnings: "Do not stop taking suddenly without consulting a doctor.",
      batch_number: "ST23456",
      country_of_origin: "Canada",
      barcode: "2345678901234",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 26,
      name: "Fluoxetine",
      quantity: 65,
      arrival_date: "2024-02-28",
      expiry_date: "2025-02-28",
      rack_number: "Z26",
      manufactured_by: "HealthCare",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Fluoxetine",
      price: 12.99,
      dosage: "20 mg",
      composition: "Fluoxetine",
      category: "Antidepressant",
      formulation: "Capsule",
      instructions: "Take 1 capsule daily in the morning.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause nausea or headache.",
      warnings: "May take several weeks to feel full effects.",
      batch_number: "UV45678",
      country_of_origin: "UK",
      barcode: "4567890123456",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 27,
      name: "Hydroxyzine",
      quantity: 70,
      arrival_date: "2024-02-26",
      expiry_date: "2025-02-26",
      rack_number: "A27",
      manufactured_by: "MediPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Hydroxyzine",
      price: 10.49,
      dosage: "25 mg",
      composition: "Hydroxyzine",
      category: "Antihistamine",
      formulation: "Tablet",
      instructions: "Take 1 tablet as needed for itching or anxiety.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause drowsiness or dry mouth.",
      warnings: "Avoid alcohol while taking this medication.",
      batch_number: "BC56789",
      country_of_origin: "Germany",
      barcode: "5678901234567",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 28,
      name: "Metoclopramide",
      quantity: 95,
      arrival_date: "2024-02-24",
      expiry_date: "2025-02-24",
      rack_number: "B28",
      manufactured_by: "GlobalPharm",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Metoclopramide",
      price: 9.99,
      dosage: "10 mg",
      composition: "Metoclopramide",
      category: "Prokinetic",
      formulation: "Tablet",
      instructions: "Take 1 tablet 30 minutes before meals and at bedtime.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause drowsiness or diarrhea.",
      warnings: "Do not take if allergic to metoclopramide.",
      batch_number: "CD67890",
      country_of_origin: "India",
      barcode: "6789012345678",
      generic_equivalent: false,
      packaging: "Blister Pack",
      special_features: "",
    },
    {
      id: 29,
      name: "Bupropion",
      quantity: 100,
      arrival_date: "2024-02-22",
      expiry_date: "2025-02-22",
      rack_number: "C29",
      manufactured_by: "BioPharma",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Bupropion",
      price: 11.49,
      dosage: "150 mg",
      composition: "Bupropion",
      category: "Antidepressant",
      formulation: "Tablet",
      instructions: "Take 1 tablet daily in the morning.",
      prescription_required: true,
      storage_conditions: "Store in a cool, dry place.",
      side_effects: "May cause insomnia or dry mouth.",
      warnings: "Do not take if you have seizures or eating disorders.",
      batch_number: "DE78901",
      country_of_origin: "Switzerland",
      barcode: "7890123456789",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
    {
      id: 30,
      name: "Fluticasone",
      quantity: 85,
      arrival_date: "2024-02-20",
      expiry_date: "2025-02-20",
      rack_number: "D30",
      manufactured_by: "PharmaCorp",
      image_url: "https://dummyimage.com/200x200/000/fff&text=Fluticasone",
      price: 10.99,
      dosage: "50 mcg",
      composition: "Fluticasone",
      category: "Corticosteroid",
      formulation: "Nasal Spray",
      instructions: "Use 2 sprays in each nostril once daily.",
      prescription_required: true,
      storage_conditions: "Store at room temperature.",
      side_effects: "May cause nasal irritation or nosebleeds.",
      warnings: "Avoid getting in eyes. Rinse eyes thoroughly if exposed.",
      batch_number: "FG12345",
      country_of_origin: "Canada",
      barcode: "1234567890123",
      generic_equivalent: false,
      packaging: "Bottle",
      special_features: "",
    },
  ];

  return (
    <>
      <Navbar />
      <div className="tablets-Card">
        <h1>Tablets</h1>
        <div className="tablet-grid">
          {tablets.map((tablet) => (
            <TabletCard key={tablet.id} tablet={tablet} />
          ))}
        </div>
      </div>
    </>
  );
};

export default Tablets;
